apiVersion: v1
kind: Service
metadata:
  name: markus-server
  namespace: markus
  labels:
    app: markus
spec:
  type: ClusterIP
  ports:
    - port: 8056
      targetPort: 8056
      name: api
    - port: 8058
      targetPort: 8058
      name: comm
    - port: 9000
      targetPort: 9000
      name: feishu-webhook
  selector:
    app: markus
    component: server
